# Basic Notes of " NUMPY "

In [193]:
import numpy as np 

# All about numpy 

In [194]:
# to create an array 
arr = np.array([3,6,33,2])

arr1 = np.array([[3,2,1,12,9], [1,2,3,4,5]], np.int8)


In [195]:
# for shape of array 
np.shape(arr1)
arr1.dtype              # for int type 

dtype('int8')

In [196]:
# Changes 
arr1[0,1] = 45
# print(arr1)
arr1

array([[ 3, 45,  1, 12,  9],
       [ 1,  2,  3,  4,  5]], dtype=int8)

### Methods to create numpy array 

1. Using python objects (displayed above)
2. Using numpy functions 

## Array creation : 

1. Conversion from other python structures

In [197]:
listarr = np.array([[1,2,3,4,5], [9,8,7,6,5]])

In [198]:
listarr.dtype

dtype('int32')

In [199]:
listarr

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [200]:
# listarr.size
listarr.shape

(2, 5)

2. Intrinsic numpy array creation objects 

In [201]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [202]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [203]:
rng = np.arange(15)

In [204]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [205]:
Ispace = np.linspace(1,4,8)     # 1 to 8 and 4 elements 

In [206]:
Ispace 

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [207]:
emp = np.empty((4,5))           # Random elements of 4*5

In [208]:
emp_like = np.empty_like(Ispace)        # forms a copy of previous array i.e emp

In [209]:
emp 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [210]:
emp_like

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        ])

In [211]:
ide = np.identity(45)           # for identity matrix of 45 * 45

In [212]:
ide 

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [213]:
ide.shape

(45, 45)

In [214]:
arr2 = np.arange(99)            # A 1D array upto range upto n 

In [215]:
arr2.reshape(3,33)          # to reshape in best matrix ( n*m = original value , i.e [ 3*33 = 99 ] )

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [216]:
ar = arr2.ravel()           # converting existing array into a 1D array 

In [217]:
ar.shape

(99,)

# Axis in numpy 

In [218]:
# Asis starts from 1 , 
# 1D array -> Axis 0
# 2D array -> Axis 0, Axis 1
# 3D array -> Axis 0, Axis 1, Axis 3
# and so on .....

# "n" dimensions have "n" axis , like x , y and z graph 


In [219]:
# Axis

x = [[1,2,3], [4,5,6], [7,1,0]]

In [220]:
ar = np.array(x)

In [221]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [222]:
ar.sum(axis=0)          # sum of x axis 

array([12,  8,  9])

In [223]:
ar.sum(axis=1)          # sum of y axis 

array([ 6, 15,  8])

In [224]:
ar.T                    # Transpose of ar array row into column and vise-versa 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [225]:
ar.flat             # it will provide iterator for iterating values of array  

In [226]:
for item in ar.flat:
    print(item)    

1
2
3
4
5
6
7
1
0


In [227]:
ar.ndim             # for dimensions 

2

In [228]:
ar.size             # for size for array

9

In [229]:
ar.nbytes           # tells how much bytes are taking by array 

36

In [230]:
one = np.array([6,8,9,0,3,12])

In [231]:
one.argmax()        # index of max element 

5

In [232]:
one.argmin()        # index of min element

3

In [233]:
one.argsort()       # sorted element's index 

array([3, 4, 0, 1, 2, 5], dtype=int64)

In [234]:
ar.argmax()        # max or min of every element's axis 

6

In [235]:
ar.argsort()        # sorted element's index of list inside array 

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [236]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [237]:
ar2 = np.array([
    [4,5,7],
    [6,1,0],
    [6,1,0]
])

In [238]:
# array addition, or simply we can do matrix addition, sub, multi, div ....
ar + ar2 
# ar * ar2

array([[ 5,  7, 10],
       [10,  6,  6],
       [13,  2,  0]])

In [239]:
ar.max()            # for max, min elements inside array  

7

## Some kind of conditions  

In [240]:
np.where(ar>5)          # returns the max where greater then 5, output is like array index in 2D

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [241]:
np.count_nonzero(ar)        # counts the no zero elements 

8

In [242]:
np.nonzero(ar)          # for every axis x or y or z, it will give index no. ( it will ignore the index if it has zero in it )

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [243]:
ar.tolist()             # returns the python list from numpy list

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

### For knowing size of array, size of array comparison between python array and numpy array   

In [244]:
import sys

In [245]:
py_ar = [0,4,55,2]

In [246]:
np_ar = np.array(py_ar)

In [247]:
sys.getsizeof(1)        # size of element present in array 

28

In [248]:
sys.getsizeof(1) * len(py_ar)       # size of python array 

112

In [249]:
np_ar.itemsize * np_ar.size         # size of numpy array is len the python array 

16